# Jekyll theme (markdown to html)

theme: jekyll-theme-minimal
title: "JeongHo SEO - Curriculum Vitae"
# description: "Personal academic and research portfolio"
# logo: /assets/images/profile.jpg
show_downloads: false
